export const ActionTypes = {
  SET_DOG_DETAILS: "SET_DOG_DETAILS",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_FAVORITE: "ADD_FAVORITE",
  SEARCH_BY_QUERY: "SEARCH_BY_QUERY",
  FILTER_BY_PRICE_ASC: "FILTER_BY_PRICE_ASC",
  FILTER_BY_PRICE_DESC: "FILTER_BY_PRICE_DESC"
}